/*
  Sequential starter code for Final Exam Practical
  
  Jim Teresco, Siena College, CSIS 400, Fall 2017

  Parallelization completed by: 
  
  Sara Lopez

*/

#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include "timer.h"
#include <pthread.h>

#define N_MAX 25000000
#define N_THREADS 4

/* This is going to be our thread function */
void *thread(void *args ) {
  int *result=(int *)args;
  int *longest=(int *)args;
  /* we just identify ourselves by the value sent in when the thread
     was created (which happens below in the main program */
  srand48(time(NULL) * (*result ));
  
  long largest_val = 0;
  int longest_length = 0;

  /* variables needed while computing sequences */
  long n;
  long current_val;
  int sequence_len;
  int i;


  for (n = 1; n <= N_MAX; n++) {
    current_val = n;
    sequence_len = 1;

    while (current_val != 1) {

      if (current_val & 1) {
        current_val = 3 * current_val + 1;
      }
      else {
        current_val >>= 1;
      }

      if (current_val > largest_val) {
        largest_val = current_val;
      }

      sequence_len++;
    }
    if (sequence_len > longest_length) {
      longest_length = sequence_len;
    }
  }

  // printf("hello");
   printf("Largest value generated by %d thread:  %ld\t\t\t \n",*result, largest_val);
  printf("Longest sequence generated by %d thread:   %ld\t\t\t \n",*longest, longest_length);
  pthread_exit((void *)largest_val);
  pthread_exit((void *)longest_length);

}


int main(int argc, char *argv[]) {

  /* to pass to gettimeofday to get wall clock times */
  struct timeval start_all, stop_all;

  /* leaders in our search */
  // long largest_val = 0;
  //int longest_length = 0;

  /* variables needed while computing sequences */
  // long n;
  //long current_val;
  //int sequence_len;
  int i, rc;
  long* results= malloc(sizeof(long)*N_THREADS);

  pthread_t threads[N_THREADS];
  
  gettimeofday(&start_all, NULL);

 
  for(i=0;i<N_THREADS;i++){
    results[i]=i;
    rc=pthread_create(&threads[i], NULL, thread, (void *)&(results[i]));
    if (rc != 0) {
    fprintf(stderr,"Could not create child thread 1\n");
    }
    /* Wait for each child thread to call pthread_exit() */
  }
  for(i=0; i <N_THREADS ; i++){
    pthread_join(threads[i], NULL);
  }

  gettimeofday(&stop_all, NULL);
  printf("Total elapsed time: %f seconds\n", diffgettime(start_all, stop_all));
  /* 

  // would get the largest_val and longest_length from results[i] but 
  forgot how to do so.
  for(i=0; i<N_THREADS;i++){

    printf("Largest value generated: %ld\n", largest_val);

    printf("Longest sequence generated: %d\n", longest_length);
  }
  */
  return 0;
}

